In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

In [4]:
data = pd.read_csv("Cryptocurrency_FeaturedData.csv")

In [5]:
data

,SNo,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap,Daily_Return,30_Day_MA,Daily_Price_Change,Daily_High_Low_Spread,Daily_Percentage_Change,7_Day_Moving_Avg,30_Day_Moving_Avg,7_Day_Volatility,30_Day_Volatility,Crypto
0,1,Bitcoin,BTC,2013-04-29 23:59:59,147.488007,134.000000,134.444000,144.539993,0.000000e+00,1.603769e+09,0.000000,0.000000,10.095993,13.488007,0.000000,0.000000,0.000000,0.000000,0.000000,Bitcoin
1,2,Bitcoin,BTC,2013-04-30 23:59:59,146.929993,134.050003,144.000000,139.000000,0.000000e+00,1.542813e+09,-3.832845,0.000000,-5.000000,12.879990,-3.832845,0.000000,0.000000,0.000000,0.000000,Bitcoin
2,3,Bitcoin,BTC,2013-05-01 23:59:59,139.889999,107.720001,139.000000,116.989998,0.000000e+00,1.298955e+09,-15.834534,0.000000,-22.010002,32.169998,-15.834534,0.000000,0.000000,0.000000,0.000000,Bitcoin
3,4,Bitcoin,BTC,2013-05-02 23:59:59,125.599998,92.281898,116.379997,105.209999,0.000000e+00,1.168517e+09,-10.069236,0.000000,-11.169998,33.318100,-10.069236,0.000000,0.000000,0.000000,0.000000,Bitcoin
4,5,Bitcoin,BTC,2013-05-03 23:59:59,108.127998,79.099998,106.250000,97.750000,0.000000e+00,1.085995e+09,-7.090580,0.000000,-8.500000,29.028000,-7.090580,0.000000,0.000000,0.000000,0.000000,Bitcoin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6588,1438,Binance Coin,BNB,2021-07-02 23:59:59,290.621683,277.350302,287.754456,287.423094,1.133633e+09,4.410016e+10,-0.275940,333.657595,-0.331363,13.271381,-0.275940,291.241158,333.657595,8.084767,43.091357,BinanceCoin
6589,1439,Binance Coin,BNB,2021-07-03 23:59:59,302.605867,283.434010,287.215592,298.237117,1.113777e+09,4.575938e+10,3.762406,329.338568,11.021525,19.171857,3.762406,293.926740,329.338568,6.472046,39.688351,BinanceCoin
6590,1440,Binance Coin,BNB,2021-07-04 23:59:59,314.713019,292.787370,298.113557,307.732096,1.387396e+09,4.721623e+10,3.183701,326.549794,9.618539,21.925649,3.183701,296.378893,326.549794,8.047080,38.084423,BinanceCoin
6591,1441,Binance Coin,BNB,2021-07-05 23:59:59,307.684855,293.523465,307.684855,302.377980,1.504870e+09,4.639473e+10,-1.739863,323.614665,-5.306875,14.161390,-1.739863,298.213731,323.614665,7.682281,36.344703,BinanceCoin
6592,1442,Binance Coin,BNB,2021-07-06 23:59:59,321.520965,302.195584,302.195584,320.934802,2.203265e+09,4.924196e+10,6.136962,321.185152,18.739217,19.325381,6.136962,301.174196,321.185152,11.583105,33.839617,BinanceCoin

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6593 entries, 0 to 6592
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   SNo                      6593 non-null   int64
 1   Name                     6593 non-null   object
 2   Symbol                   6593 non-null   object
 3   Date                     6593 non-null   object
 4   High                     6593 non-null   float64
 5   Low                      6593 non-null   float64
 6   Open                     6593 non-null   float64
 7   Close                    6593 non-null   float64
 8   Volume                   6593 non-null   float64
 9   Marketcap                6593 non-null   float64
 10  Daily_Return             6593 non-null   float64
 11  30_Day_MA                6593 non-null   float64
 12  Daily_Price_Change       6593 non-null   float64
 13  Daily_High_Low_Spread    6593 non-null   float64
 14  Daily_Percentage_Change  6593 non-null   float64
 15  7_Day_Moving_Avg         6593 non-null   float64
 16  30_Day_Moving_Avg        6593 non-null   float64
 17  7_Day_Volatility         6593 non-null   float64
 18  30_Day_Volatility        6593 non-null   float64
 19  Crypto                   6593 non-null   object
dtypes: float64(15), int64(1), object(4)
memory usage: 1.0+ MB

In [7]:
data['Date'] = pd.to_datetime(data['Date'])

In [8]:
data['month'] = data['Date'].dt.month

In [9]:
data['Day'] = data['Date'].dt.day
data['year'] = data['Date'].dt.year

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6593 entries, 0 to 6592
Data columns (total 23 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   SNo                      6593 non-null   int64
 1   Name                     6593 non-null   object
 2   Symbol                   6593 non-null   object
 3   Date                     6593 non-null   datetime64[ns]
 4   High                     6593 non-null   float64
 5   Low                      6593 non-null   float64
 6   Open                     6593 non-null   float64
 7   Close                    6593 non-null   float64
 8   Volume                   6593 non-null   float64
 9   Marketcap                6593 non-null   float64
 10  Daily_Return             6593 non-null   float64
 11  30_Day_MA                6593 non-null   float64
 12  Daily_Price_Change       6593 non-null   float64
 13  Daily_High_Low_Spread    6593 non-null   float64
 14  Daily_Percentage_Change  6593 non-null   float64
 15  7_Day_Moving_Avg         6593 non-null   float64
 16  30_Day_Moving_Avg        6593 non-null   float64
 17  7_Day_Volatility         6593 non-null   float64
 18  30_Day_Volatility        6593 non-null   float64
 19  Crypto                   6593 non-null   object
 20  month                    6593 non-null   int32
 21  Day                      6593 non-null   int32
 22  year                     6593 non-null   int32
dtypes: datetime64[ns](1), float64(15), int32(3), int64(1), object(3)
memory usage: 1.1+ MB

In [11]:
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
6588    False
6589    False
6590    False
6591    False
6592    False
Length: 6593, dtype: bool

In [12]:
data.duplicated().sum()

0

In [13]:
data.Crypto.nunique()

3

In [14]:
data.Crypto.value_counts()

Crypto
Bitcoin        2991
Ethereum       2160
BinanceCoin    1442
Name: count, dtype: int64

In [15]:
data.isna().sum()

SNo                        0
Name                       0
Symbol                     0
Date                       0
High                       0
Low                        0
Open                       0
Close                      0
Volume                     0
Marketcap                  0
Daily_Return               0
30_Day_MA                  0
Daily_Price_Change         0
Daily_High_Low_Spread      0
Daily_Percentage_Change    0
7_Day_Moving_Avg           0
30_Day_Moving_Avg          0
7_Day_Volatility           0
30_Day_Volatility          0
Crypto                     0
month                      0
Day                        0
year                       0
dtype: int64

In [16]:
data.head()

,SNo,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap,...,Daily_High_Low_Spread,Daily_Percentage_Change,7_Day_Moving_Avg,30_Day_Moving_Avg,7_Day_Volatility,30_Day_Volatility,Crypto,month,Day,year
0,1,Bitcoin,BTC,2013-04-29 23:59:59,147.488007,134.000000,134.444000,144.539993,0.0,1.603769e+09,...,13.488007,0.000000,0.0,0.0,0.0,0.0,Bitcoin,4,29,2013
1,2,Bitcoin,BTC,2013-04-30 23:59:59,146.929993,134.050003,144.000000,139.000000,0.0,1.542813e+09,...,12.879990,-3.832845,0.0,0.0,0.0,0.0,Bitcoin,4,30,2013
2,3,Bitcoin,BTC,2013-05-01 23:59:59,139.889999,107.720001,139.000000,116.989998,0.0,1.298955e+09,...,32.169998,-15.834534,0.0,0.0,0.0,0.0,Bitcoin,5,1,2013
3,4,Bitcoin,BTC,2013-05-02 23:59:59,125.599998,92.281898,116.379997,105.209999,0.0,1.168517e+09,...,33.318100,-10.069236,0.0,0.0,0.0,0.0,Bitcoin,5,2,2013
4,5,Bitcoin,BTC,2013-05-03 23:59:59,108.127998,79.099998,106.250000,97.750000,0.0,1.085995e+09,...,29.028000,-7.090580,0.0,0.0,0.0,0.0,Bitcoin,5,3,2013

In [17]:
data = data.drop('Date', axis = 1)

In [18]:
data['Name'].value_counts()

Name
Bitcoin         2991
Ethereum        2160
Binance Coin    1442
Name: count, dtype: int64

In [19]:
data['Crypto'].value_counts()

Crypto
Bitcoin        2991
Ethereum       2160
BinanceCoin    1442
Name: count, dtype: int64

In [20]:
data = data.drop(columns = ['Name', 'Symbol'])

In [21]:
d = {'Bitcoin' : 0,
    'Ethereum' : 1,
    'BinanceCoin':2}

In [22]:
data['crypto_label'] = data['Crypto'].map(d)

In [23]:
data.select_dtypes(['int','float']).corrwith(data['crypto_label'])

SNo                       -0.397024
High                      -0.350807
Low                       -0.353339
Open                      -0.351645
Close                     -0.351866
Volume                    -0.266722
Marketcap                 -0.300347
Daily_Return               0.038087
30_Day_MA                 -0.350884
Daily_Price_Change        -0.011958
Daily_High_Low_Spread     -0.262534
Daily_Percentage_Change    0.038087
7_Day_Moving_Avg          -0.351649
30_Day_Moving_Avg         -0.350884
7_Day_Volatility          -0.292284
30_Day_Volatility         -0.301568
month                      0.001840
Day                        0.000640
year                       0.390032
crypto_label               1.000000
dtype: float64

In [55]:
data = data.drop(columns = ['Crypto'])

In [57]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6593 entries, 0 to 6592
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   SNo                      6593 non-null   int64
 1   High                     6593 non-null   float64
 2   Low                      6593 non-null   float64
 3   Open                     6593 non-null   float64
 4   Close                    6593 non-null   float64
 5   Volume                   6593 non-null   float64
 6   Marketcap                6593 non-null   float64
 7   Daily_Return             6593 non-null   float64
 8   30_Day_MA                6593 non-null   float64
 9   Daily_Price_Change       6593 non-null   float64
 10  Daily_High_Low_Spread    6593 non-null   float64
 11  Daily_Percentage_Change  6593 non-null   float64
 12  7_Day_Moving_Avg         6593 non-null   float64
 13  30_Day_Moving_Avg        6593 non-null   float64
 14  7_Day_Volatility         6593 non-null   float64
 15  30_Day_Volatility        6593 non-null   float64
 16  month                    6593 non-null   int32
 17  Day                      6593 non-null   int32
 18  year                     6593 non-null   int32
 19  crypto_label             6593 non-null   int64
dtypes: float64(15), int32(3), int64(2)
memory usage: 953.0 KB

In [59]:
data.head()

,SNo,High,Low,Open,Close,Volume,Marketcap,Daily_Return,30_Day_MA,Daily_Price_Change,Daily_High_Low_Spread,Daily_Percentage_Change,7_Day_Moving_Avg,30_Day_Moving_Avg,7_Day_Volatility,30_Day_Volatility,month,Day,year,crypto_label
0,1,147.488007,134.000000,134.444000,144.539993,0.0,1.603769e+09,0.000000,0.0,10.095993,13.488007,0.000000,0.0,0.0,0.0,0.0,4,29,2013,0
1,2,146.929993,134.050003,144.000000,139.000000,0.0,1.542813e+09,-3.832845,0.0,-5.000000,12.879990,-3.832845,0.0,0.0,0.0,0.0,4,30,2013,0
2,3,139.889999,107.720001,139.000000,116.989998,0.0,1.298955e+09,-15.834534,0.0,-22.010002,32.169998,-15.834534,0.0,0.0,0.0,0.0,5,1,2013,0
3,4,125.599998,92.281898,116.379997,105.209999,0.0,1.168517e+09,-10.069236,0.0,-11.169998,33.318100,-10.069236,0.0,0.0,0.0,0.0,5,2,2013,0
4,5,108.127998,79.099998,106.250000,97.750000,0.0,1.085995e+09,-7.090580,0.0,-8.500000,29.028000,-7.090580,0.0,0.0,0.0,0.0,5,3,2013,0

In [61]:
X = data.drop('crypto_label', axis=1)
y = data['crypto_label']

In [63]:
train_X, test_X, train_y, test_y = train_test_split(X,y , test_size=0.2, random_state=42)

In [66]:
#Random FOrest
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

# Define hyperparameter grid
pargrid_ada = {
    'n_estimators': [50, 60, 70, 80, 90, 100],
    'max_features': [2, 3, 4],
    'max_depth': [2, 3, 4, 5, 6]
}

# Perform grid search with cross-validation
gscv_Rf = GridSearchCV(
    estimator=RandomForestClassifier(),
    param_grid=pargrid_ada,
    cv=5,
    verbose=True,
    n_jobs=-1,
    scoring='accuracy'
).fit(train_X, train_y)

Fitting 5 folds for each of 90 candidates, totalling 450 fits

In [68]:
print(gscv_Rf.best_params_)
print(gscv_Rf.best_score_)

{'max_depth': 6, 'max_features': 4, 'n_estimators': 70}
0.9916587677725118

In [70]:
radm_clf = RandomForestClassifier(oob_score=True,n_estimators=100 , max_depth = 6, max_features=3, n_jobs=-1)
radm_clf.fit( train_X, train_y )

RandomForestClassifier(max_depth=6, max_features=3, n_jobs=-1, oob_score=True)

In [72]:
from sklearn import metrics

# Train AUC
print("Train AUC:", metrics.roc_auc_score(train_y, radm_clf.predict_proba(train_X), multi_class='ovr'))

# Test AUC
print("Test AUC:", metrics.roc_auc_score(test_y, radm_clf.predict_proba(test_X), multi_class='ovr'))

Train AUC: 0.9999371614946618
Test AUC: 0.9998368632407342

In [74]:
radm_clf.oob_score_

0.9787637466818354